starting_coordinates_dict = {
    "white_pawn_1": [50, 650],
    "white_pawn_2": [150, 650],
    "white_pawn_3": [250, 650],
    "white_pawn_4": [350, 650],
    "white_pawn_5": [450, 650],
    "white_pawn_6": [550, 650],
    "white_pawn_7": [650, 650],
    "white_pawn_8": [750, 650],
    "white_rook_1": [50, 750],
    "white_knight_1": [150, 750],
    "white_bishop_1": [250, 750],
    "white_queen": [350, 750],
    "white_king": [450, 750],
    "white_bishop_2": [550, 750],
    "white_knight_2": [650, 750],
    "white_rook_2": [750, 750],
    "black_pawn_1": [50, 150],
    "black_pawn_2": [150, 150],
    "black_pawn_3": [250, 150],
    "black_pawn_4": [350, 150],
    "black_pawn_5": [450, 150],
    "black_pawn_6": [550, 150],
    "black_pawn_7": [650, 150],
    "black_pawn_8": [750, 150],
    "black_rook_1": [50, 50],
    "black_knight_1": [150, 50],
    "black_bishop_1": [250, 50],
    "black_queen": [350, 50],
    "black_king": [450, 50],
    "black_bishop_2": [550, 50],
    "black_knight_2": [650, 50],
    "black_rook_2": [750, 50]
}

piece_positions_dict = {
    "white_pawn_1": "a2",
    "white_pawn_2": "b2",
    "white_pawn_3": "c2",
    "white_pawn_4": "d2",
    "white_pawn_5": "e2",
    "white_pawn_6": "f2",
    "white_pawn_7": "g2",
    "white_pawn_8": "h2",
    "white_rook_1": "a1",
    "white_knight_1": "b1",
    "white_bishop_1": "c1",
    "white_queen": "d1",
    "white_king": "e1",
    "white_bishop_2": "f1",
    "white_knight_2": "g1",
    "white_rook_2": "h1",
    "black_pawn_1": "a7",
    "black_pawn_2": "b7",
    "black_pawn_3": "c7",
    "black_pawn_4": "d7",
    "black_pawn_5": "e7",
    "black_pawn_6": "f7",
    "black_pawn_7": "g7",
    "black_pawn_8": "h7",
    "black_rook_1": "a8",
    "black_knight_1": "b8",
    "black_bishop_1": "c8",
    "black_queen": "d8",
    "black_king": "e8",
    "black_bishop_2": "f8",
    "black_knight_2": "g8",
    "black_rook_2": "h8"
}

lettered_to_numeric = {
    "a": 1,
    "b": 2,
    "c": 3,
    "d": 4,
    "e": 5,
    "f": 6,
    "g": 7,
    "h": 8
}

numeric_to_lettered = {
    1: "a",
    2: "b",
    3: "c",
    4: "d",
    5: "e",
    6: "f",
    7: "g",
    8: "h"
}

notation_dict = {
    "white_pawn_1": "",
    "white_pawn_2": "",
    "white_pawn_3": "",
    "white_pawn_4": "",
    "white_pawn_5": "",
    "white_pawn_6": "",
    "white_pawn_7": "",
    "white_pawn_8": "",
    "white_rook_1": "R",
    "white_knight_1": "N",
    "white_bishop_1": "B",
    "white_queen": "Q",
    "white_king": "K",
    "white_bishop_2": "B",
    "white_knight_2": "N",
    "white_rook_2": "R",
    "black_pawn_1": "",
    "black_pawn_2": "",
    "black_pawn_3": "",
    "black_pawn_4": "",
    "black_pawn_5": "",
    "black_pawn_6": "",
    "black_pawn_7": "",
    "black_pawn_8": "",
    "black_rook_1": "R",
    "black_knight_1": "N",
    "black_bishop_1": "B",
    "black_queen": "Q",
    "black_king": "K",
    "black_bishop_2": "B",
    "black_knight_2": "N",
    "black_rook_2": "R",
    "white_queen_A": "Q",
    "black_queen_A": "Q",
    "white_rook_A": "R",
    "black_rook_A": "R",
    "white_bishop_A": "B",
    "black_bishop_A": "B",
    "white_knight_A": "N",
    "black_knight_A": "N",
}
